Feat/current location nearest station #13
sophie-app/sophie pull request #18
Opened 2024-11-05 13:59 UTC by imoken777

close #13 
# backend
- `stationUseCase`に最寄り駅取得メソッド`getNearestStation`追加
- そのためのutlis
- 仮でそれようのエンドポイント`/location`追加

# frontend
- 現在地取得のためのカスタムフック追加

2024-11-05 14:43 UTC, mst-mkt requested changes

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/usecases/stationUseCase.ts
> +      params: { path: { RDF_TYPE: 'odpt:Station' }, query: { lat, lon, radius: 4000 } },
`4000`は定数に切り出したさがある

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/utils/calculateSphericalDistance.ts
> +  const R = 6371 // 地球の半径（km）
`toRadians`と`R`は関数外で定義してもいいかも

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/utils/calculateSphericalDistance.ts
> +  const toRadians = (degree: number) => degree * (Math.PI / 180)
`degreeToRadians`みたいな命名の方がわかりやすそう

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/utils/calculateSphericalDistance.ts
> +  lon2: number,
`1`,`2`だと混乱しそうだから`from`,`to`みたいな命名のほうが好み

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/routes/location.ts
> +    if (!nearestStation) {
これは好き嫌い分かれると思うんだけど、
```ts
if (!nullishableObject) {}
```
で弾くより、
```ts
if (nullishableObject !== null) {}
```
```ts
if (nullishableObject !== undefined) {}
```
とかで弾くほうがどういう場合で分岐したいのかぱっとわかって好きなんだけどどう思う？

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/routes/location.ts
> +      return c.text('Internal server error', 500)
エラー内容もうちょい書いてもいいかも

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/usecases/stationUseCase.ts
> +  getNearestStation: async (lat: number, lon: number, odptClient: Client<paths>) => {
`./src/lib/odptApiPath.ts`で
```ts
export type odptClient = Client<paths> // このファイル内では`paths`は別名かも
```
したさが若干ある

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/usecases/stationUseCase.ts
> +    const stations = res.data
```ts
const { data: stations } = await odptClient.Get( // 省略
```
でもいいかも

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/usecases/stationUseCase.ts
> +    })
reduse使うよりはmapしてMath.minに渡したほうが意図がわかりやすそう

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/routes/location.ts
> +    if (!nearestStation) {
ここでundefinedかどうかで分岐するより、stationUseCasesでstationsがundefineのとき例外を投げてその例外をここでキャッチしたいかも

2024-11-05 14:43 UTC, mst-mkt commented on apps/backend/src/utils/calculateSphericalDistance.ts
> +  const dLon = toRadians(lon2 - lon1)
変数名あんま省略しなくていいよ
dLatとかだとわからん

2024-11-05 15:23 UTC, imoken777 commented on apps/backend/src/usecases/stationUseCase.ts
> +    })
それってこういうことよね？
こっからどうやってstation自体を返せば良いのかわからぬ
```ts
Math.min(
      ...stations.map((station) =>
        calculateSphericalDistance(
          { lat, lon },
          { lat: station['geo:lat'], lon: station['geo:long'] },
        ),
      ),
    )
```

2024-11-05 15:25 UTC, mst-mkt commented on apps/backend/src/usecases/stationUseCase.ts
> +    })
あ、たしかにこれじゃだめかも...... ごめん

2024-11-05 15:26 UTC, imoken777 commented on apps/backend/src/usecases/stationUseCase.ts
> +    })
おｋ

2024-11-05 16:05 UTC, mst-mkt requested changes

2024-11-05 16:05 UTC, mst-mkt commented on apps/backend/src/lib/odptApiPath.ts
> +export type OdptClient = Client<OmitApiKeyFromPaths>
`exprt { hoge, fuga }`でまとめたさあるかも？

```suggestion
type OdptClient = Client<OmitApiKeyFromPaths>

export type { OmitApiKeyFromPaths as paths, OdptClient }
```

2024-11-05 16:05 UTC, mst-mkt commented on apps/backend/src/index.ts
> +  .route('/location', locationRoute)
今更だけど最寄り駅が`location`なのかは謎

2024-11-05 16:05 UTC, mst-mkt commented on apps/backend/src/routes/location.ts
> +  .post('/', vValidator('json', postReqBodySchema), async (c) => {
apiの内容的にはgetのほうが良さそう

2024-11-07 01:01 UTC, mst-mkt commented on apps/backend/src/utils/calculateSphericalDistance.ts
> +  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
公式か何かを使った複雑な計算は、コメントアウトで補足しておいたほうがわかりやすそう

2024-11-07 01:01 UTC, mst-mkt commented on apps/backend/src/utils/calculateSphericalDistance.ts
> +  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
関数に切り出してJSDoc的なの書いておきたさがある

2024-11-07 10:21 UTC, imoken777 commented on apps/backend/src/utils/calculateSphericalDistance.ts
> +  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
関数分けるとよりわかりずらそうだったから関数にjsdocと途中計算にはコメントアウトにした
それでもよくわからないけど

2024-11-09 14:35 UTC, mst-mkt approved these changes

2024-11-09 14:35 UTC, merged